#!/bin/bash

if (( $# != 1 )); then
    echo "USAGE: $0 csv_file" >&2
    exit 1
fi

CSV_FILE=$1
CLEANED_FILE=${1}.clean
cp $CSV_FILE $CLEANED_FILE
while IFS= read -r line; do
    replacement=$(cat ./payees.txt | fzf --header="$line")
    if [[ -n "$replacement" ]]; then
        original=$(echo "$line" | perl -wlne '/"(.*)"/ and print $1')
        perl -i -wlpe "s/\Q$original\E/$replacement/" $CLEANED_FILE
    fi
done < $CSV_FILE
