#!/bin/bash

if (( $# != 1 )); then
    echo "USAGE: $0 REST_ENDPOINT"
    exit 1
fi

REST_ENDPOINT=$1

curl -s \
    -H "Content-type: application/json" \
    -H "Authorization: Bearer $(jq -r .token ~/.ynab)" \
    https://api.youneedabudget.com/v1/budgets/$(jq -r .budget_id ~/.ynab)/$REST_ENDPOINT \
    -d @-

